### ISSUE TITLE
Add variables in the scenario template

### ISSUE THREAD

**Issue by bapboitier** [iiasa/eu-climate-advisory-board-workflow#4]
We would like to add some variables in the scenario template either because we think they are highly relevant when looking at EU mitigation policy (in green) or because they were in the previous versions, such AR6 sceanrio templates (in orange).
We added this variable at the end of the variables list in the file [here](https://docs.google.com/spreadsheets/d/1n2ldqDvnsxvDufP7t-XfSWsnhMFvhgqu/edit?usp=sharing&ouid=102535926570122823774&rtpof=true&sd=true).

**Comment by danielhuppmann** [comment]
Thank you for the suggestion of additional sub-categories. Note that the suggested variables "...|Solids|Fossils" are basically duplicates of the existing "...|Solids|Coal", so please use those instead to avoid confusion.
